### ISSUE TITLE
What's the training settings for track_1 and track_2 model

### ISSUE THREAD

**Issue by flyers** [glample/Arnold#4]
First of all thanks for releasing the source code for the successful training of Doom agents.
The pretrained models contain the winner model of the last year's competition. May I know what's the exact training setting for those two models? Does it requires some curriculum learning stages?
Thanks very much.

**Comment by glample** [comment]
Hi,

The `run.sh` file here https://github.com/glample/Arnold/blob/master/run.sh will contain the running commands to visualize the agents, and these commands also contain the training parameters. The parameters we used that are not specified in the commands are the default ones in the code.

We did not use curriculum learning or anything like this, although it might help a bit.

**Comment by flyers** [comment]
Hi,
Thanks for your quick reply. I will try to reproduce this from scratch.
By the way, how long does it take for the model to reach the performance of the released ones?

**Comment by glample** [comment]
On a P100 it should take a couple of days.

**Comment by flyers** [comment]
I used the following command to train a model on track_1.
```bash
python3 arnold.py --exp_name track_1 --main_dump_path $PWD/dumped \
--frame_skip 3 --action_combinations "attack+move_lr;turn_lr;move_fb" \
--network_type "dqn_rnn" --recurrence "lstm" --n_rec_layers 1 --hist_size 4 --remember 1 \
--labels_mapping "" --game_features "target,enemy" --bucket_size "[10, 1]" --dropout 0.5 \
--speed "on" --crouch "off" --map_ids_test 1 --manual_control 1 \
--scenario "deathmatch" --wad "deathmatch_rockets" --gpu_id 0
```
The training process runs up to 10119600 iterations while the log shows that the best performance model is best-120000.pth, achieving a frag score of 62. I also note that the variance of the frags score is quite large between different iterations. Is that normal?

**Comment by glample** [comment]
What is the K/D ratio? The number of frags isn't necessarily very relevant because a bot can get quite a good number of frags by shooting randomly. Did you visualize the agent to have a look at how it behaves?

Regarding the variance between different iterations, this is normal yes. Variance should decrease if you increase the evaluation time, but the number of frags usually oscillates quite a lot (as opposed to the K/D which is usually more stable).

**Comment by Maxwell2017** [comment]
> I used the following command to train a model on track_1.
> 
> ```shell
> python3 arnold.py --exp_name track_1 --main_dump_path $PWD/dumped \
> --frame_skip 3 --action_combinations "attack+move_lr;turn_lr;move_fb" \
> --network_type "dqn_rnn" --recurrence "lstm" --n_rec_layers 1 --hist_size 4 --remember 1 \
> --labels_mapping "" --game_features "target,enemy" --bucket_size "[10, 1]" --dropout 0.5 \
> --speed "on" --crouch "off" --map_ids_test 1 --manual_control 1 \
> --scenario "deathmatch" --wad "deathmatch_rockets" --gpu_id 0
> ```
> 
> The training process runs up to 10119600 iterations while the log shows that the best performance model is best-120000.pth, achieving a frag score of 62. I also note that the variance of the frags score is quite large between different iterations. Is that normal?

Hello flyers. Did you reproduce the Pretrain model? I don't know if it is caused by my parameter setting. After three days of training, the track1 result is not very high, K/D ratio less than 1 @flyers
