### ISSUE TITLE
How to combine LSTM and experience replay

### ISSUE THREAD

**Issue by chenlheng** [glample/Arnold#7]
I notice that you use replay buffer with experience decomposed into independent screens, while processing these screens with a LSTM layer. From my point of view, LSTM has a strong relationship with temporal sequence and seems to be unsuitable for this kind of usage. Did I miss anything?

**Comment by glample** [comment]
The screens are stored in a sequential order in the replay memory, so if the LSTM is used for training then the trainer will sample sequences of screens as opposed to individual screens. Of course these sequences are not going to be full sequences starting from the beginning of the episode (that would be too expensive) so we feed usually the last 5 frames to initialize the LSTM hidden state.

**Comment by chenlheng** [comment]
Thanks. This explanation makes sense to me.
